### ISSUE TITLE
not install

### ISSUE THREAD

**Issue by Elduquecarlo** [viher3/trimestral-perfexcrm-module#2]
Hello friend good day, It does not install on the new Perfex update, is it possible that you can fix it?

**Comment by viher3** [comment]
Hi, 

I will check it soon.

Stay tuned for updates.

**Comment by Elduquecarlo** [comment]
hello friend thank you very much

**Comment by viher3** [comment]
Hello @Elduquecarlo and sorry for delay in responding.

I have updated my PerfexCRM to latest version (3.0.6) and the module works fine.
Have you installed the module correctly? Or maybe you have not completed the installation successfully?.

Please, give me more feedback about your problem.

**Comment by Elduquecarlo** [comment]
Hello Alberto thank you very much, if it worked for me happy day
